### ISSUE TITLE
Most macros should be wrapped in do{...}while(0)

### ISSUE THREAD

**Issue by KarolS** [ollelogdahl/ihct#2]
### Steps to reproduce:

```
#include <ihct.h>

IHCT_TEST(test1) {
    if (0) IHCT_FAIL();
    IHCT_FAIL();
}

int main(int argc, char **argv) {
    return IHCT_RUN(argc, argv);
}
```

### What was expected:

* The second IHCT_FAIL fires and the test fails.

### What actually happened:

* The second IHCT_FAIL was skipped and the entire suite succeeded.

### Suggested fix: 

1. Define IHCT_FAIL as follows:

```
#define IHCT_FAIL() do {result->status = FAIL; return; } while (0)
````

2. Do the same for other multistatement macros.

Wrapping statements in `do { ... } while (0)` is the standard way of defining such macros.

**Comment by ollelogdahl** [comment]
Seems you're right, that case would need to be handled. Wouldn't simply wrapping in a block scope `{ ... }` work? Don't see the need for the `do { ... } while(0)`.

EDIT:
This was solved by simply moving all macros with multiple expressions into block.

**Comment by KarolS** [comment]
Still doesn't work as it should, the following doesn't compile at all now:

```c
#include <ihct.h>

IHCT_TEST(test1) {
    if (0) IHCT_FAIL();
    else IHCT_FAIL();
}

int main(int argc, char **argv) {
    return IHCT_RUN(argc, argv);
}
```

```
test.c: In function ‘test_test1’:
test.c:4:2: error: ‘else’ without a previous ‘if’
  else IHCT_FAIL();
  ^~~~
```

https://stackoverflow.com/questions/154136/why-use-apparently-meaningless-do-while-and-if-else-statements-in-macros

**Comment by ollelogdahl** [comment]
Sorry that i jumped to conclusions. Yeah you're right. I'll be fixing this immedietly! Thank you for reporting it! :)
